
set(TARGET_DIRECTORY ${CMAKE_BINARY_DIR}/target)
set(TARGET_BIN_DIRECTORY ${TARGET_DIRECTORY}/bin)
set(TARGET_LIB_DIRECTORY ${TARGET_DIRECTORY}/lib)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${TARGET_LIB_DIRECTORY})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${TARGET_LIB_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TARGET_BIN_DIRECTORY})
